version: 2.1

orbs:
  whitesource-scan: whitesource/whitesource-scan@18.10.2

workflows:
  wssc:
    jobs:
      - scws: # a sample job that would be defined above.
          steps:
            - whitesource-scan/scan: #invokes the sync command declared in the s3 orb
                api_key: aebb4302e6dd4fdfa91c3a90969acd4691ee38b6afb143e1bf2e9f1a2d96a6fe

#jobs:
#  ws:
#    steps:
#      - run: bash < (curl -s -L https://github.com/whitesource/unified-agent-distribution/raw/master/standAlone/wss_agent.sh) -apiKey aebb4302e6dd4fdfa91c3a90969acd4691ee38b6afb143e1bf2e9f1a2d96a6fe -project circle-ci_test -d ~/

