version: 2.1
description: "The orb integrates WhiteSource Unified Agent, a tool which extracts descriptive information from your open source libraries located on your file system. For more information: https://whitesource.atlassian.net/wiki/spaces/WD/pages/33718339/Unified+Agent"

executors:
  java:
    description: The docker container to run java commands
    docker:
      - image: circleci/openjdk:8-jdk

jobs:
  scan:
    executor: java
    steps:
      - checkout
      - run:
          command: |
              apt update
      - run:
          command: |
              apt install php
      - run:
          command: |
              curl -s https://getcomposer.org/installer | php
      - run:
          command: |
              mv composer.phar /usr/local/bin/composer
      - run:
          command: |
              bash <(curl -s -L https://github.com/whitesource/unified-agent-distribution/raw/master/standAlone/wss_agent.sh) -logLevel debug -apiKey "aebb4302e6dd4fdfa91c3a90969acd4691ee38b6afb143e1bf2e9f1a2d96a6fe" -c "./wss-unified-agent.config" -project circle-ci_test -d ~/ 
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - scan